#!/bin/bash
echo "Starting MRS program"
echo "===================="

sh ../src/compile

# classpaths for running are separated by ':'
# -ea is --enableassertions
java -ea -cp .:../lib/json-simple-1.1.1.jar:./../bin/ ralgorithm.Run$1
