#!/bin/bash
echo "Starting MRS program"
echo "===================="
javac -cp ./json-simple-1.1.1.jar -g -d . *.java
#java -cp ./json-simple-1.1.1.jar src.TestSlide
java -cp .:./json-simple-1.1.1.jar src.TestParallelMove
