#!/bin/bash
echo "Starting MRS program"
echo "===================="

sh compile

# classpaths for running are separated by ':'
# -ea is --enableassertions
if [ $1 = "Robot" ]
then
    java -ea -cp .:../lib/json-simple-1.1.1.jar:./../bin/ rgraph.Test$1
else
    if [ $1 = "RobotStats" ]
    then
        java -ea -cp .:../lib/json-simple-1.1.1.jar:./../bin/ rutils.Test$1
    else
        java -ea -cp .:../lib/json-simple-1.1.1.jar:./../bin/ ralgorithm.Test$1
    fi
fi
