#!/bin/bash
echo "Starting MRS program"
echo "===================="

sh compile

# classpaths for running are separated by ':'
if [ $1 = "Robot" ]
then
    java -cp .:../lib/json-simple-1.1.1.jar:./../bin/ rgraph.Test$1
else
    java -cp .:../lib/json-simple-1.1.1.jar:./../bin/ ralgorithm.Test$1
fi
